env: shipcombat

env_args:
  field_reward: False
  PBRS: True
  alpha: 2
  beta: 5
  r1: 0.3
  r2: 0.4
  r3: 0.4



  replay_dir: "results/test"
  replay_prefix: ""
  seed: null
  start_pos: null

  gamma: 0.99
  n_ships: 2
  n_reds: 1 #红船数量
  n_blues: 1 #蓝船数量
  n_agents: 2

  radar_range: 50
  fire_range: 20  # 打击距离
  fire_angle: 0.39269908169872414   # 打击范围1/8*np.pi
  max_health: 20


